### ISSUE TITLE
[FEATURE REQUEST] - IMAP Folder option

### ISSUE THREAD

**Issue by nodecentral** [Skyleiger/email-to-paperless#10]
HI @Skyleiger 

Hope all is well, 

I wanted to ask if it was possible to have an option to just target the folder(s) you want to scan, rather than have to list out everything you don’t ? I have so many folders I need to exclude :-))

**Comment by Skyleiger** [comment]
Hi, @nodecentral 

I can implement such a possibility. 

I'll get on it this weekend and implement also the possibility to put the emails into a folder like the consume folder, as you told me a few days ago.

You will see a new version at the beginning of the next week.

**Comment by nodecentral** [comment]
Many thanks @Skyleiger

**Comment by Skyleiger** [comment]
Hi, version 1.1.0 is online including your suggestions. Have a look.

**Comment by nodecentral** [comment]
Hi @Skyleiger -

Many thanks for doing this, although I’m not sure how to configure it?

All i still seem to have is the `IMAP_EXCLUDED_FOLDERS` Environment option ?

**Comment by Skyleiger** [comment]
Hi @nodecentral 

I'm sorry, I forgot to extend the readme.
You can use the `IMAP_INCLUDED_FOLDERS` environment variable to specify the folders you want to scan.
