### ISSUE TITLE
Set up guide, and supported IMAP providers

### ISSUE THREAD

**Issue by nodecentral** [Skyleiger/email-to-paperless#5]
Hi, 

Many thanks for posting this…

I’ve just started to invest time in setting up Paperless-ngx (via Docker) and this looks to be a key piece of that set up, however I’m not entirely sure I understand the setup or the IMAP providers that it can support, and if I have more than one how is that best facilitated.

Starting with the set up, my Paperless instance, uses postgresql, does that matter in this i situation, as you’re using mariadb and I’m not familiar with that at all? Also, is a dB needed ? I Only ask as I already have a ``consume` folder set up on a mapped drive to ingest content, therefore I was wondering if there a facility to write / map pdf/attachment output from your Docker directly to that same consume folder ?

As for the IMAP providers, Ive seen some reports of the likes of MS (Outlook) and Google (GMail) moving away from IMAP, have you tested it with many of those players, of is this more for a locally hosted set up ?

Sorry for all the questions..

**Comment by Skyleiger** [comment]
Hi,

i'm not sure if you understand my application.

The database that my application needs, MariaDB, is completely independent of the Paperless database and has nothing to do with it.
In it I only store the emails that I have already read.

The application can read emails from any email provider that provides an IMAP interface. However, it is also true that large providers such as Google or Microsoft neglect IMAP, but still support IMAP at the current state (can be activated in the settings of the provider).

An instance of my application can read emails from a provider. If you have multiple providers, you need to run multiple instances of my application accordingly.

Please excuse the delay in replying.

**Comment by nodecentral** [comment]
Thanks @Skyleiger - I’ve been learning quite a few things since i posted that original message, I was literally just starting out.. Really appreciate your responding,..

**Comment by Skyleiger** [comment]
> Thanks @Skyleiger - I’ve been learning quite a few things since i posted that original message, I was literally just starting out.. Really appreciate your responding,..

Wonderful. So can the issue be closed?

**Comment by nodecentral** [comment]
Yes please close - many thanks
