### ISSUE TITLE
[FEATURE REQUEST] - Have the ability to write to a local mapped folder/volume.

### ISSUE THREAD

**Issue by nodecentral** [Skyleiger/email-to-paperless#7]
Hi

Just wanted to post the idea for this app to be enhanced so you have an option to write all generated emails/pdfs to a local/mapped folder/volume rather than directly to Paperless.

**Comment by Skyleiger** [comment]
> Hi
> 
> Just wanted to post the idea for this app to be enhanced so you have an option to write all generated emails/pdfs to a local/mapped folder/volume rather than directly to Paperless.

Hi, should this step happen together with the upload to Paperless or should the whole thing run completely without Paperless. In the latter case I would not be sure if a separate application would not be a better choice.

**Comment by nodecentral** [comment]
Hi @Skyleiger, 

It can actually work in both scenarios, as the target folder could be set and the Paperless `consume` folder. 

For me personally i like to have the option of sending things to a `pre-consumption` folder, a space which gives me the chance to make any changes i need to the document (i.e if a pdf, split, combine/merge etc.) before passing it on to Paperless.

**Comment by Skyleiger** [comment]
> Hi @Skyleiger,
> 
> It can actually work in both scenarios, as the target folder could be set and the Paperless `consume` folder.
> 
> For me personally i like to have the option of sending things to a `pre-consumption` folder, a space which gives me the chance to make any changes i need to the document (i.e if a pdf, split, combine/merge etc.) before passing it on to Paperless.

Oh yes, sure. That's a nice idea I think. I can see if I can implement such a feature.

**Comment by Skyleiger** [comment]
Hi, version 1.1.0 is online including your suggestions. Have a look.

**Comment by nodecentral** [comment]
Thanks @Skyleiger , although I do have a similar question to my other post, how best do I set this up ?

**Comment by Skyleiger** [comment]
Hi @nodecentral 

The best solution is to map your paperless `consume` folder as a folder into the email-to-paperless container.

For example, if you map your `consume` folder to `/usr/share/paperless/consume` into the container, you have to simply set the environment variables
`EMAIL_STORING_STRATEGY` to `FOLDER` and
`EMAIL_STORING_FOLDER` to `/usr/share/paperless/consume`.

With that, you can remove all environment variables starting with `PAPERLESS...`.
